FROM php:8.1-apache

RUN a2enmod rewrite
RUN apt-get update -y
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN apt-get install -y git zlib1g-dev libpng-dev libgd-dev libzip-dev unzip libsodium-dev libxml2-dev
RUN docker-php-ext-install zip mysqli pdo_mysql gd sodium soap
RUN mkdir -p /var/www/back

WORKDIR /var/www/back

CMD [ "php", "./test.php" ]
